config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope '/', module: :web, as: :web do
    root "home#index"
  end

  scope '/admin', module: :admin, as: :admin do
    root 'movies_dashboard#index'
    resources :movies
    devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_one_attached :photo
  belongs_to :user
  validates :user_id, presence: true
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 500 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :movies
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false }, 
  format: { with: VALID_EMAIL_REGEX }
  before_save { self.email = email.downcase }
end

app/controllers/admin/movies_controller.rb
module Admin
  class MoviesController < AdminController
    
    def new
      @movie = Movie.new
    end  

    def create
      @movie = Movie.new(admin_movie_params)
      @movie.user = current_admin_user
      if @movie.save
        redirect_to admin_movie_path(@movie)
      else
        render 'new'
      end
    end

    def show
      @movie = Movie.find(params[:id])
    end
    
    def edit
      @movie = Movie.find(params[:id])
    end  

    def update
      @movie = Movie.find(params[:id])
      if @movie.update(admin_movie_params)
        redirect_to admin_movie_path(@movie)
      else
        render 'edit'
      end
    end

    def destroy
      @movie = Movie.find(params[:id])
      @movie.destroy
      redirect_to admin_root_path
    end

    
    private
      def admin_movie_params
        params.require(:movie).permit(:title, :description, :genres, :original_language, :photo)
      end
  end
end

app/controllers/admin/movies_dashboard_controller.rb
module Admin
  class MoviesDashboardController < AdminController
    
    def index
      @movies = Movie.all
    end
    
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin_user!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  def create
    # user = User.find_by(email: resource_params[:email])
    # if user.present?
    #   token, hashed = Devise.token_generator.generate(User, :reset_password_token)
    #   user.reset_password_token = hashed
    #   user.reset_password_sent_at = Time.now
    #   if user.save
    #     host = request.base_url
    #     SendgridEmail.new().forgot_password(user.email, token, host)
    #     redirect_to new_web_user_session_path, flash: { success: I18n.t('devise.passwords.send_instructions') }
    #   else
    #     redirect_to new_web_user_password_path, flash: { error: 'Email invalid' }
    #   end
    # else
    #   redirect_to new_web_user_password_path, flash: { error: 'Email invalid' }
    # end
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  def update
    # self.resource = resource_class.reset_password_by_token(resource_params)
    # yield resource if block_given?

    # if resource.errors.empty?
    #   resource.unlock_access! if unlockable?(resource)
    #   set_flash_message!(:notice, :updated_not_active)
    #   respond_with resource, location: new_session_path(resource_name)
    # else
    #   respond_with resource
    # end
  end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  # respond_to :html

  # GET /resource/sign_in
  # def new
  #   super
  #   byebug
  # end

  private
    # def respond_with(resource, _opts = {})
    #   # render :new
    # end
  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/web/home_controller.rb
module Web
  class HomeController < WebController
    def index
      @movies = Movie.all
    end
  end
end

app/controllers/web_controller.rb
class WebController < ApplicationController
  layout 'web'

end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class?(path)
    return 'active' if current_page?(path)
  end
end

app/helpers/svg_helper.rb
module SvgHelper
  def svg_use file, options = {}
    content_tag :svg, options do
    content_tag :use, nil, :'xlink:href' => asset_path(file)
    end
  end 
end

app/views/admin/movies/_form.html.slim
=form_for @movie, url: admin_movies_path(@movie), html: {class: 'popup__form'} do |f|
  .popup__fieldset
    .popup__row
      .popup__field.field
        .field__label Movie title
        .field__wrap
          = f.text_field :title, class: 'field__input'
      .popup__field.field
          .field__label Genres
          .field__wrap
            = f.text_field :genres, class: 'field__input'
    .popup__row
      .popup__field.field
        .field__label Language
        .field__wrap
          = f.text_field :original_language, class: 'field__input'
      .popup__field.field
        .field__label Photo
        .field__wrap
          .popup__loading
            = f.file_field :photo, accept: 'image/png,image/jpeg', class: 'popup__file'
            button.popup__btn.btn.btn_purple Upload Photo
    .popup__row
      .popup__field.field.field_custom
        .field__label Description
        .field__wrap
          = f.text_area :description, class: 'field__textarea'
    button.popup__btn.btn.btn_black.mt-5 type="submit" Update
  

app/views/admin/movies/edit.html.slim
=form_for @movie, url: admin_movie_path(@movie), html: {class: 'popup__form'} do |f|
  .popup__title.h6 Edit movie
  .popup__fieldset
    .popup__row
      .popup__field.field
        .field__label Movie title
        .field__wrap
          = f.text_field :title, class: 'field__input'
      .popup__field.field
          .field__label Genres
          .field__wrap
            = f.text_field :genres, class: 'field__input'
    .popup__row
      .popup__field.field
        .field__label Description
        .field__wrap
          = f.text_area :description, class: 'field__textarea'
      .popup__field.field
        .field__label Language
        .field__wrap
          = f.text_field :original_language, class: 'field__input'
        button.popup__btn.btn.btn_black.mt-5 type="submit" Update
  

app/views/admin/movies/index.html.slim
.page__row.page__row_border
  .page__col
    h3 New movies 
    = render 'form'
  .page__col
    .page__group
      .widget.widget_stat.widget_shadow.widget_after
        .widget__chart.widget__chart_items
          #chart-earnings-by-item
        .widget__title Earnings By Item
        .widget__counter.title.title_md 479.4
        .widget__text.widget__text_mb40 Update your payout method in Settings
        .widget__legend
          .widget__color
            .widget__bg style=("background: #3a4dd6;") 
            .widget__text Templates
          .widget__color
            .widget__bg style=("background: #FFA2C0;") 
            .widget__text Themes
      .widget.widget_shadow.widget_after
        .widget__title.mr-auto Your Top Items
        .quality.quality_big
          .quality__list
            a.quality__item href="#" 
              .quality__preview.bg-pink-opacity
                = image_tag('wallets/images/figure-1.png', class: "quality__pic")
              .quality__details
                .quality__category.title
                  | Unity UI Kit
                  = svg_use('wallets/images/sprite.svg#icon-arrow-right', class: 'icon icon-arrow-right')
                .quality__info.caption-sm UI Design
                .quality__money.caption $64
            a.quality__item href="#" 
              .quality__preview.bg-pink-opacity
                = image_tag('wallets/images/figure-2.png', class: "quality__pic")
              .quality__details
                .quality__category.title
                  | Unity UI Kit
                  = svg_use('wallets/images/sprite.svg#icon-arrow-right', class: 'icon icon-arrow-right')
                .quality__info.caption-sm UI Design
                .quality__money.caption $64
            a.quality__item href="#" 
              .quality__preview.bg-blue-light
                = image_tag('wallets/images/figure-6.png', class: "quality__pic")
              .quality__details
                .quality__category.title
                  | Unity UI Kit
                  = svg_use('wallets/images/sprite.svg#icon-arrow-right', class: 'icon icon-arrow-right')
                .quality__info.caption-sm UI Design
                .quality__money.caption $64
            a.quality__item href="#" 
              .quality__preview.bg-yellow
                = image_tag('wallets/images/figure-4.png', class: "quality__pic")
              .quality__details
                .quality__category.title
                  | Unity UI Kit
                  = svg_use('wallets/images/sprite.svg#icon-arrow-right', class: 'icon icon-arrow-right')
                .quality__info.caption-sm UI Design
                .quality__money.caption $64
          button.quality__btn.btn.btn_black.btn_wide Show all report

app/views/admin/movies/new.html.slim
.page__row.page__row_border
  .page__col
    h3 New movies 
    = render 'form'

app/views/admin/movies_dashboard/index.html.slim
.page__content
  .banner
    .banner__container
      .banner__preview
        = image_tag('wallets/images/banner-pic.png', class: "banner__pic")
      .banner__wrap
        .banner__title.h3 Unique views this month 5678 views
        = link_to 'Add New Movie', new_admin_movie_path, class:'banner__btn btn btn_white'
  .page__stat.page__stat_pt32
    .sorting
      .sorting__row
        .sorting__col
          .sorting__dropdowns
            .dropdown.js-dropdown
              .dropdown__head.js-dropdown-head Last 30 days
              .dropdown__body.js-dropdown-body
                a.dropdown__item href="#" 
                  .dropdown__title.title Bento 3D Kit
                  .dropdown__info.caption Illustration
                a.dropdown__item href="#" 
                  .dropdown__title.title Bento 3D Kit
                  .dropdown__info.caption Illustration
                a.dropdown__item href="#" 
                  .dropdown__title.title Collab UI Kit
                  .dropdown__info.caption Coded Template
            .dropdown.js-dropdown
              .dropdown__head.js-dropdown-head Aug 2020
              .dropdown__body.js-dropdown-body
                a.dropdown__item href="#" 
                  .dropdown__title.title Bento 3D Kit
                  .dropdown__info.caption Illustration
                a.dropdown__item href="#" 
                  .dropdown__title.title Bento 3D Kit
                  .dropdown__info.caption Illustration
                a.dropdown__item href="#" 
                  .dropdown__title.title Collab UI Kit
                  .dropdown__info.caption Coded Template
        .sorting__col
          .sorting__line
            .sorting__search
              button.sorting__open
                = svg_use('wallets/images/sprite.svg#icon-search', class: 'icon icon-search')
              input.sorting__input placeholder="Search" type="text" /
            .sorting__actions
              button.sorting__action
                = svg_use('wallets/images/sprite.svg#icon-edit', class: 'icon icon-edit')
              button.sorting__action
                = svg_use('wallets/images/sprite.svg#icon-box', class: 'icon icon-box')
    .products.products_main
      .products__table
        .products__row.products__row_head
          .products__cell Title
          .products__cell Language
          .products__cell Status
          .products__cell Genres
          .products__cell Rating
          .products__cell Delete
        - if @movies.present?
          - @movies.each do |movie|
            .products__row
              .products__cell
                =link_to admin_movie_path(movie), class:'products__item' do
                  .products__previeww
                    - if movie.photo.attached?
                      = image_tag(movie.photo, class: "products__pic")
                  .products__details
                    .products__title.title  = movie.title
                    .products__info.caption.color-gray.movie_desc = movie.description
              .products__cell
                .products__payment = movie.original_language
              .products__cell
                .products__color
                  .products__bg style=("background-color: #3a4dd6;") 
                  .products__text Visible
              .products__cell
                .products__cost
                  .products__money = movie.genres
              .products__cell
                .products__rating
                  span.color-green 5.0
                  | (45 votes)
              .products__cell
                .sorting__actions
                  =button_to admin_movie_path(movie), method: :delete, class:'sorting__action', data: {confirm: "Are you sure?"} do
                    = svg_use('wallets/images/sprite.svg#icon-edit', class: 'icon icon-edit')
          / .products__more
          /   button.products__btn.btn.btn_black Load More

app/views/layouts/_admin_footer.html.slim
= javascript_include_tag 'admin'

app/views/layouts/_admin_page_title.html.slim
.page-title-box
  .row.align-items-center
    .col-sm-6
      h4.page-title Dashboard
    .col-sm-6
      ol.breadcrumb.float-right
        li.breadcrumb-item
          a href="javascript:void(0);"  xGT
        li.breadcrumb-item.active Dashboard
  /! end row

app/views/layouts/_header.html.slim
#preloader
  = image_tag('home/logo1.png', class: "footer-logo")
  #status
    span
    span
header.ht-header
  .container
    nav.navbar.navbar-default.navbar-custom
      .navbar-header.logo
        .navbar-toggle data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" 
          span.sr-only Toggle navigation
          #nav-icon1
            span
            span
            span
        a href="index.html" 
          = image_tag('home/logo1.png', width:'119', height: '58', class: "logo")
      #bs-example-navbar-collapse-1.collapse.navbar-collapse.flex-parent
        ul.nav.navbar-nav.flex-child-menu.menu-left
          li.hidden
            a href="#page-top" 
          li.dropdown.first
            a.btn.btn-default.dropdown-toggle.lv1 data-toggle="dropdown" 
              | Home
              i.fa.fa-angle-down aria-hidden="true" 
            ul.dropdown-menu.level1
              li
                a href="index.html"  Home 01
              li
                a href="homev2.html"  Home 02
              li
                a href="homev3.html"  Home 03
          li.dropdown.first
            a.btn.btn-default.dropdown-toggle.lv1 data-hover="dropdown" data-toggle="dropdown" 
              | movies
              i.fa.fa-angle-down aria-hidden="true" 
            ul.dropdown-menu.level1
              li.dropdown
                a.dropdown-toggle data-toggle="dropdown" href="#" 
                  | Movie grid
                  i.ion-ios-arrow-forward
                ul.dropdown-menu.level2
                  li
                    a href="moviegrid.html"  Movie grid
                  li
                    a href="moviegridfw.html"  movie grid full width
              li
                a href="movielist.html"  Movie list
              li
                a href="moviesingle.html"  Movie single
              li.it-last
                a href="seriessingle.html"  Series single
          li.dropdown.first
            a.btn.btn-default.dropdown-toggle.lv1 data-hover="dropdown" data-toggle="dropdown" 
              | celebrities
              i.fa.fa-angle-down aria-hidden="true" 
            ul.dropdown-menu.level1
              li
                a href="celebritygrid01.html"  celebrity grid 01
              li
                a href="celebritygrid02.html"  celebrity grid 02
              li
                a href="celebritylist.html"  celebrity list
              li.it-last
                a href="celebritysingle.html"  celebrity single
          li.dropdown.first
            a.btn.btn-default.dropdown-toggle.lv1 data-hover="dropdown" data-toggle="dropdown" 
              | news
              i.fa.fa-angle-down aria-hidden="true" 
            ul.dropdown-menu.level1
              li
                a href="bloglist.html"  blog List
              li
                a href="bloggrid.html"  blog Grid
              li.it-last
                a href="blogdetail.html"  blog Detail
          li.dropdown.first
            a.btn.btn-default.dropdown-toggle.lv1 data-hover="dropdown" data-toggle="dropdown" 
              | community
              i.fa.fa-angle-down aria-hidden="true" 
            ul.dropdown-menu.level1
              li
                a href="userfavoritegrid.html"  user favorite grid
              li
                a href="userfavoritelist.html"  user favorite list
              li
                a href="userprofile.html"  user profile
              li.it-last
                a href="userrate.html"  user rate
        ul.nav.navbar-nav.flex-child-menu.menu-right
          li.dropdown.first
            a.btn.btn-default.dropdown-toggle.lv1 data-hover="dropdown" data-toggle="dropdown" 
              | pages
              i.fa.fa-angle-down aria-hidden="true" 
            ul.dropdown-menu.level1
              li
                a href="landing.html"  Landing
              li
                a href="404.html"  404 Page
              li.it-last
                a href="comingsoon.html"  Coming soon
          li
            a href="/aaa"  Help
          - if current_admin_user.present?
            li.btn.signupLink
              = link_to 'Logout', destroy_admin_user_session_path, method: "get"
          - else
            li.loginLink
              = link_to 'Login', admin_user_session_path, class:""
            li.btn.signupLink
              = link_to 'Sign up', new_admin_user_registration_path, class:""
    form action="#" 
      .top-search
        select
          option value="united"  TV show
          option value="saab"  Others
        input placeholder=("Search for a movie, TV Show or celebrity that you are looking for") type="text" /

app/views/layouts/admin.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    meta content=("IE=edge") http-equiv="X-UA-Compatible" /
    meta content=("width=device-width, initial-scale=1") name="viewport" /
    meta content=("") name="description" /
    meta content=("") name="keywords" /
    title Nudo Cinema | Manager
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'admin', media: 'all'
  body
    main.page
      = render 'layouts/wallets/sidebar'
      .page__wrapper
        .page__center
          = render 'layouts/wallets/header'
          = yield
  = javascript_include_tag 'admin'

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title MovieApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    / = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield

app/views/layouts/wallets/_header.html.slim
.page__row.page__row_head
  .page__col
    .page__hello.h5= "Hi Nudo"
    .page__welcome.h2
      | Welcome back
      span.desktop-hide 👋
  .page__col
    .header
      button.header__burger
      .notifications
        button.notifications__open
          = svg_use('wallets/images/sprite.svg#icon-bell', class: 'icon icon-bell')
          span.notifications__counter
        .notifications__wrap
          / .notifications__info.h6
          /   | Recent Notification
          / .notifications__list
          /   a.notifications__item href="#" 
          /     .notifications__ava
          /       = image_tag('wallets/images/ava-1.png', class: "notifications__pic")
          /       .notifications__status.bg-blue
          /         = image_tag('wallets/images/chat.svg', class: "notifications__pic")
          /     .notifications__details
          /       .notifications__line
          /         .notifications__user.caption
          /           | Sarah Saunders
          /         .notifications__time.caption 8h
          /       .notifications__text.caption-sm
          /         | Commented on
          /         span.notifications__project Collab Design
          /   a.notifications__item href="#" 
          /     .notifications__ava
          /       = image_tag('wallets/images/ava-1.png', class: "notifications__pic")
          /       .notifications__status.bg-green
          /         = image_tag('wallets/images/bag.svg', class: "notifications__pic")
          /     .notifications__details
          /       .notifications__line
          /         .notifications__user.caption
          /           | Glenn Greer
          /         .notifications__time.caption 12h
          /       .notifications__text.caption-sm
          /         | Just pushaded
          /         span.notifications__project Sapiens Illustration
          /   a.notifications__item href="notifications.html" 
          /     .notifications__ava
          /       = image_tag('wallets/images/ava-1.png', class: "notifications__pic")
          /       .notifications__status.bg-purple
          /         = image_tag('wallets/images/message.svg', class: "notifications__pic")
          /     .notifications__details
          /       .notifications__line
          /         .notifications__user.caption
          /           | Sarah Saunders
          /         .notifications__time.caption 14h
          /       .notifications__text.caption-sm
          /         | Sent you a message 📪
          /   a.notifications__item href="notifications.html" 
          /     .notifications__ava
          /       = image_tag('wallets/images/ava-1.png', class: "notifications__pic")
          /       .notifications__status.bg-red
          /         = image_tag('wallets/images/heart.svg', class: "notifications__pic")
          /     .notifications__details
          /       .notifications__line
          /         .notifications__user.caption
          /           | Sarah Saunders
          /         .notifications__time.caption 21h
          /       .notifications__text.caption-sm
          /         | Liked
          /         span.notifications__project Folio Agency
          /   a.notifications__item href="notifications.html" 
          /     .notifications__ava
          /       = image_tag('wallets/images/ava-1.png', class: "notifications__pic")
          /       .notifications__status.bg-blue
          /         = image_tag('wallets/images/chat.svg', class: "notifications__pic")
          /     .notifications__details
          /       .notifications__line
          /         .notifications__user.caption
          /           | Sarah Saunders
          /         .notifications__time.caption 8h
          /       .notifications__text.caption-sm
          /         | Commented on
          /         span.notifications__project Collab Design
          /   a.notifications__item href="notifications.html" 
          /     .notifications__ava
          /       = image_tag('wallets/images/ava-1.png', class: "notifications__pic")
          /       .notifications__status.bg-green
          /         = image_tag('wallets/images/bag.svg', class: "notifications__pic")
          /     .notifications__details
          /       .notifications__line
          /         .notifications__user.caption
          /           | Glenn Greer
          /         .notifications__time.caption 12h
          /       .notifications__text.caption-sm
          /         | Just pushaded
          /         span.notifications__project Sapiens Illustration
          / .notifications__btns
            a.notifications__btn.btn.btn_black href="#"  See all incoming activity
      .sidebar__profile
        a.sidebar__user href="#" 
          .sidebar__ava
            = image_tag('wallets/images/ava.png', class: "sidebar__pic")
          .sidebar__desc
            / .sidebar__man= current_web_user.email.split('@')[0]
            / .sidebar__status.caption Free account
          .sidebar__arrow
            = svg_use('wallets/images/sprite.svg#icon-arrows', class: 'icon icon-arrows')
        .sidebar__details
          = link_to '#', class: 'sidebar__link text-danger'
            .sidebar__icon
              = svg_use('wallets/images/sprite.svg#icon-profile', class: 'icon icon-profile')
            .sidebar__text Profile
          = link_to destroy_admin_user_session_path, method: "get", class: 'sidebar__link' do
            .sidebar__icon
              = svg_use('wallets/images/sprite.svg#icon-logout', class: 'icon icon-logout')
            .sidebar__text Log out
          / a.sidebar__link href="#" 
          /   .sidebar__icon
          /     = svg_use('wallet/images/sprite.svg#icon-logout', class: 'icon icon-logout')
          /   .sidebar__text Log out
      / a.header__user href="#" 
      /   = image_tag('wallets/images/ava.png', class: "header__pic")

app/views/layouts/wallets/_sidebar.html.slim
.sidebar
  .sidebar__top
    button.sidebar__close
      = svg_use('wallets/images/sprite.svg#icon-close', class: 'icon icon-close')
    a.sidebar__logo href="#"
      = image_tag('home/logo1.png', class: "sidebar__pic sidebar__pic_black", width: 100)
      = image_tag('home/logo1.png', class: "sidebar__pic sidebar__pic_white", width: 100)
    button.sidebar__burger
  .sidebar__wrapper
    .sidebar__inner
      a.sidebar__logo href="#"
        = image_tag('home/logo1.png', class: "sidebar__pic logo-sm")
      .sidebar__list
        .sidebar__group
          .sidebar__caption
            | Nudo
            span Cinema
          .sidebar__menu
            = link_to admin_root_path, class: "sidebar__item #{active_class?(admin_root_path)}" do
              .sidebar__icon
                = svg_use('wallets/images/sprite.svg#icon-overview', class: 'icon icon-overview')
              .sidebar__text Dashboard
            = link_to '#', class: "sidebar__item #{active_class?(web_root_path)}" do
              .sidebar__icon
                = svg_use('wallets/images/sprite.svg#icon-chart', class: 'icon icon-bag')
              .sidebar__text Bookmark
            = link_to '#', class: "sidebar__item #{active_class?(web_root_path)}" do
              .sidebar__icon
                = svg_use('wallets/images/sprite.svg#icon-wallet', class: 'icon icon-wallet')
              .sidebar__text History
            = link_to '#', class: "sidebar__item #{active_class?(web_root_path)}" do
              .sidebar__icon
                = svg_use('wallets/images/sprite.svg#icon-wallet', class: 'icon icon-wallet')
              .sidebar__text Subscriptions
            = link_to '#', class: "sidebar__item #{active_class?(web_root_path)}" do
              .sidebar__icon
                = svg_use('wallets/images/sprite.svg#icon-document', class: 'icon icon-document')
              .sidebar__text Movie Liked
            = link_to '#', class: "sidebar__item #{active_class?(web_root_path)}" do
              .sidebar__icon
                = svg_use('wallets/images/sprite.svg#icon-settings', class: 'icon icon-settings')
              .sidebar__text Settings
  .sidebar__bottom
    label.switch.switch_theme.js-switch-theme
      input.switch__input type="checkbox" /
      span.switch__in
        span.switch__box
        span.switch__icon
          svg.icon.icon-moon
            use xlink:href="wallets/images/sprite.svg#icon-moon"
          svg.icon.icon-sun
            use xlink:href="wallets/images/sprite.svg#icon-sun"

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>